blank_issues_enabled: false
contact_links:
  - name: ✏️ Post-processing / Editing Transcripts
    url: https://github.com/cjpais/Handy/discussions/168
    about: Looking to edit, format, or post-process transcripts? Join this discussion
  - name: ⌨️ Keyboard Shortcuts / Hotkeys
    url: https://github.com/cjpais/Handy/discussions/211
    about: Want different keyboard shortcuts or hotkey configurations? Join this discussion
  - name: 💡 Feature Request or Idea
    url: https://github.com/cjpais/Handy/discussions
    about: Please post feature requests and ideas in our Discussions tab
  - name: 💬 General Discussion
    url: https://github.com/cjpais/Handy/discussions
    about: Ask questions and discuss Handy with the community
